#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

echo '开始代码格式检查与修正'
npm run lint-staged
echo "代码格式化检查完毕"

# npm test

# STAGE_FILES=$(git diff --cached --name-only -- '*.json' '*.js' '*.vue')
# if test ${#STAGE_FILES} -gt 0
# then
#     for FILE in $STAGE_FILES
#     do
        
#         if [[ "$?" == 1 ]]; then
#       PASS=false
#     fi
#   done

# else
#     echo '没有js或者json文件需要检查'
# fi

exit 0

